### ISSUE TITLE
How to run test

### ISSUE THREAD

**Issue by galliroberto** [CoinageCrypto/lamington#259]
I tryed to run test
```nmp t```

> lamington test

⠸ Stopping EOS Docker ContainerError response from daemon: No such container: lamington
✖ { Error: Error: stdout , stderr Error response from daemon: No such container: lamington

```
{
    "name": "xxx",
    "version": "1.0.0",
    "description": "xxx",
    "main": "app.js",
    "dependencies": {
        "body-parser": "^1.19.0",
        "eosjs": "^20.0.3",
        "express": "^4.17.1",
        "node-fetch": "^2.6.0"
    },
    "devDependencies": {
        "lamington": "^1.0.0-alpha.5",
        "chai": "latest",
        "@types/chai": "latest",
        "@types/mocha": "latest",
        "nodemon": "^2.0.4"
    },
    "scripts": {
        "build": "lamington build",
        "start": "lamington start eos",
        "stop": "lamington stop eos",
        "test": "lamington test"
    },
    "author": "xxx",
    "license": "xxx"
}
```

**Comment by thekevinbrown** [comment]
Hey there,

That looks like the correct setup. What happens if you run `npm start` then run `npm t`? I'm betting the test command is just trying to stop the container in case it's running but isn't actually creating it if it's not there first, which is a bug, but that will likely get you up and going in the meantime.

**Comment by thekevinbrown** [comment]
I'll assume this is resolved. If you still need help with this feel free to open another issue.
